return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "black",
      "cmakelang",
      "cmakelint",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "goimports",
      "gopls",
      "hadolint",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "pyright",
      "shfmt",
      "sqlfluff",
      "stylua",
      "yaml-language-server",
    },
  },
}
